import Navbar from "../components/Navbar";

export const metadata = {
  title: "My Next.js Site",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        style={{
          fontFamily: "sans-serif",
        }}
      >
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
