import Navbar from "../components/Navbar";
import { Open_Sans } from "next/font/google";
import "./global.css";

export const metadata = {
  title: "My Next.js Site",
  description: "Generated by Next.js",
  keywords: "nextjs, react, seo",
};

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={[openSans.className, "bg-slate-50", "scrollbar-hide"].join(
          " ",
        )}
      >
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
