import Navbar from "../components/Navbar";
import { Source_Sans_3 } from "next/font/google";
import "./global.css";

export const metadata = {
  title: "My Next.js Site",
  description: "Generated by Next.js",
  keywords: "nextjs, react, seo",
};

const sans = Source_Sans_3({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={sans.className}>
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
