import Navbar from "../components/Navbar";
import { Open_Sans } from "next/font/google";
import "./global.css";

export const metadata = {
  title: "My Next.js Site",
  description: "Generated by Next.js",
  keywords: "nextjs, react, seo",
};

const openSans = Open_Sans({ subsets: ["latin"], weight: ["400"] });

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={(openSans.className, "scrollbar-hide")}>
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
